### ISSUE TITLE
Upgrade to @temporalio 1.0.0

### ISSUE THREAD

**Issue by brianlu-scale** [KurtzL/nestjs-temporal#11]
Seems like temporalio's typescript sdk now has an official release in 1.0.0 (https://github.com/temporalio/sdk-typescript/tags). Are there plans to upgrade this package to support that? Tried upgrading the package myself in a fork, but running into some issues with the client connection.

**Comment by Prashant-Surya** [comment]
@brianlu-scale I've worked on a PR for this https://github.com/KurtzL/nestjs-temporal/pull/16
