### ISSUE TITLE
sample app 

### ISSUE THREAD

**Issue by macielcr7** [KurtzL/nestjs-temporal#15]
is there any complete example using this module?

@KurtzL ?

**Comment by Prashant-Surya** [comment]
I've added an example in my github account: https://github.com/Prashant-Surya/nestjs-temporal-example 
This uses nestjs-temporal fork with latest temporal sdk support.

Feel free to reach out to me for any help :)

**Comment by macielcr7** [comment]
> I've added an example in my github account: https://github.com/Prashant-Surya/nestjs-temporal-example This uses nestjs-temporal fork with latest temporal sdk support.
> 
> Feel free to reach out to me for any help :)

thanks for helping @Prashant-Surya
