### ISSUE TITLE
Multiple workers can not work

### ISSUE THREAD

**Issue by Engelce** [KurtzL/nestjs-temporal#22]
I have 2 namespces, and I need 2 workers handle workflow, but it can not work.
<img width="952" alt="image" src="https://user-images.githubusercontent.com/87524394/198002601-c8891a90-8960-4070-9047-6d1a9d9ad7fe.png">
![image](https://user-images.githubusercontent.com/87524394/198002922-7cf559f9-da49-4fe9-9a6b-1b0ec73d1964.png)
![image](https://user-images.githubusercontent.com/87524394/198003114-57704a1a-3a21-45e0-82ef-1765cf7d49ad.png)

**Comment by byrafaelr** [comment]
Any soluction ?
