### ISSUE TITLE
Worker NPE

### ISSUE THREAD

**Issue by rbialek** [KurtzL/nestjs-temporal#5]
I'm trying to test your plugin but of some reason I keep getting this error. Any ideas?

Thanks
RB

Debugger listening on ws://127.0.0.1:36729/7085afc2-535f-430f-94e8-d9f561398b9c
For help, see: https://nodejs.org/en/docs/inspector
Debugger attached.
[Nest] 3141873  - 05/24/2022, 2:08:38 PM     LOG [NestFactory] Starting Nest application...
[Nest] 3141873  - 05/24/2022, 2:08:38 PM     LOG [InstanceLoader] AppModule dependencies initialized +60ms
[Nest] 3141873  - 05/24/2022, 2:08:38 PM     LOG [InstanceLoader] TemporalModule dependencies initialized +0ms
[Nest] 3141873  - 05/24/2022, 2:08:38 PM     LOG [InstanceLoader] TemporalModule dependencies initialized +0ms
[Nest] 3141873  - 05/24/2022, 2:08:38 PM     LOG [InstanceLoader] DiscoveryModule dependencies initialized +1ms
[Nest] 3141873  - 05/24/2022, 2:08:38 PM     LOG [InstanceLoader] TemporalModule dependencies initialized +0ms
/home/rbialek/nest-temporal/node_modules/nestjs-temporal/dist/temporal.explorer.js:55
                yield worker_1.Core.install(coreConfig);
                                    ^
TypeError: Cannot read properties of undefined (reading 'install')
    at TemporalExplorer.<anonymous> (/home/rbialek/nest-temporal/node_modules/nestjs-temporal/dist/temporal.explorer.js:55:37)
    at Generator.next (<anonymous>)
    at fulfilled (/home/rbialek/nest-temporal/node_modules/nestjs-temporal/dist/temporal.explorer.js:14:58)
Waiting for the debugger to disconnect...

**Comment by efrengarcial** [comment]
hello @[KurtzL](https://github.com/KurtzL)  good day, I am having the same problem, I include the information you are requesting:

```json 
"dependencies": {
    "@nestjs/common": "^9.0.3",
    "@nestjs/config": "^2.2.0",
    "@nestjs/core": "^9.0.0",
    "@nestjs/mapped-types": "^1.1.0",
    "@nestjs/platform-express": "^9.0.0",
    "@nestjs/typeorm": "^9.0.0",
    "@temporalio/activity": "^1.0.0-rc.1",
    "@temporalio/client": "^1.0.0-rc.1",
    "@temporalio/worker": "^1.0.0-rc.1",
    "@temporalio/workflow": "^1.0.0-rc.1",
    "class-transformer": "^0.5.1",
    "class-validator": "^0.13.2",
    "dotenv": "^16.0.1",
    "joi": "^17.6.0",
    "nestjs-temporal": "^0.0.5",
    "pg": "^8.7.3",
    "reflect-metadata": "^0.1.13",
    "rimraf": "^3.0.2",
    "rxjs": "^7.2.0",
    "typeorm": "^0.3.7"
  },
```
```ts 
@Module({
  imports: [
    PostsModule, 
    DatabaseModule,
    ConfigModule.forRoot({
      load: [config], 
      isGlobal: true,
      cache: true,
    }),
    TemporalModule.forRoot({
      taskQueue: 'default',
      workflowsPath: require.resolve('./temporal/workflow'),
    }),
    
    TemporalModule.registerClient(),
  ],
  controllers: [AppController],
  providers: [AppService],
})
export class AppModule {}
```

Thanks a lot

**Comment by brianlu-scale** [comment]
Hey, ran into this as well. I think the problem is an incompatibility of temporalio's typescript sdk versions, where in the newer versions such as the one that @efrengarcial is using, the @temporalio/worker no longer contains a Core class. You can see the changelog here: https://github.com/temporalio/sdk-typescript/blob/main/CHANGELOG.md#0200---2022-04-06. I'm working on my own fork of this package (https://github.com/brianlu-scale/nestjs-temporal) that tries to support the temporalio/worker version of 1.0.0, but still running into some issues with client connection that I'd appreciate help from @KurtzL on.

**Comment by macielcr7** [comment]
@brianlu-scale is there any complete example using this module?

**Comment by brianlu-scale** [comment]
@macielcr7  https://github.com/brianlu-scale/nestjs-temporal is up to date. As for examples of using it, look at the README

**Comment by macielcr7** [comment]
@brianlu-scale 
using the example, in the temporal it informs that there is no worker started..
how should i called in nest?

**Comment by macielcr7** [comment]
TemporalExplorer onInvoke 
`await this.runWorker();`

`/node_modules/memfs/lib/volume.js:295
            throw new TypeError(ERRSTR.PATH_STR);
TypeError: path must be a string or Buffer`

**Comment by macielcr7** [comment]
solved this problem, maybe it's not the best way but that's how I solved it.

`workflowsPath: path.resolve(__dirname+'/temporal/workflow.js'),`

**Comment by brianlu-scale** [comment]
sorry just saw this, I think they also suggest using a workflowsBundle if you want to do that instead of passing in a workflows path

**Comment by brianlu-scale** [comment]
this seems like more of a Temporal specific issue rather than a nestjs-temporal package issue

**Comment by macielcr7** [comment]
> sorry just saw this, I think they also suggest using a workflowsBundle if you want to do that instead of passing in a workflows path

@brianlu-scale  is there an easy example?, or suggestion?

**Comment by KurtzL** [comment]
Hello @macielcr7, if you have a little trouble understanding the use of nestjs-temporal. I can try to improve the README

**Comment by macielcr7** [comment]
@KurtzL it's a good idea to improve the README

**Comment by jdnichollsc** [comment]
> @KurtzL it's a good idea to improve the README

Any pull request is welcome! :+1:

**Comment by clintonb** [comment]
For future readers who have issues with bundles: see https://docs.temporal.io/application-development/foundations#register-types. You'll need a pre-build script that bundles your TypeScript into JavaScript, and a helper that switches between `workflowsPath` and `workflowBundle` (in production).
